name: build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
      -
        name: Set up dependencies
        run: go get .
      -
        name: Build
        run: go build
      -
        name: Test
        run: go test ./...
      -
        name: Check gofmt
        run: files="$(gofmt -l .)" && echo "$files" && test -z "$files"
